run: compile 
	./listaLigadaSimple

compile: 
	gcc -c listaLigadaSimple.c -o listaLigadaSimple.o
	gcc Implementacion.c listaLigadaSimple.o -o listaLigadaSimple
clean:
	rm -rf *.o
	rm listaLigadaSimple
